In [1]:
import numpy
numpy.__version__

'1.17.2'

In [2]:
import matplotlib
matplotlib.__version__

'3.1.1'

In [3]:
import keras
keras.__version__

Using TensorFlow backend.


'2.3.1'

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import dlt
import os

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Conv2D, MaxPooling2D, Flatten
from keras.optimizers import Adam
from keras.utils.np_utils import to_categorical

In [5]:
data = dlt.cifar.load_cifar10()

170500096/170498071 [==============================] - 48s 0us/step


In [7]:
#学習用の画像とラベル
print(data.train_images.shape)
print(data.train_labels.shape)

#テスト用の画像とラベル
print(data.test_images.shape)
print(data.test_labels.shape)

(50000, 32, 32, 3)
(50000, 1)
(10000, 32, 32, 3)
(10000, 1)


In [8]:
print(data.train_images[0]) #一つ目の添字`50000`のうち、一つ目の画像のデータ

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]


In [9]:
print(data.train_images[0][0]) # [画像の番号][ピクセルの行or列方向指定]
print(data.train_images[0][0].shape)

[[ 59  62  63]
 [ 43  46  45]
 [ 50  48  43]
 [ 68  54  42]
 [ 98  73  52]
 [119  91  63]
 [139 107  75]
 [145 110  80]
 [149 117  89]
 [149 120  93]
 [131 103  77]
 [125  99  76]
 [142 115  91]
 [144 112  86]
 [137 105  79]
 [129  97  71]
 [137 106  79]
 [134 106  76]
 [124  97  64]
 [139 113  78]
 [139 112  75]
 [133 105  69]
 [136 105  74]
 [139 108  77]
 [152 120  89]
 [163 131 100]
 [168 136 108]
 [159 129 102]
 [158 130 104]
 [158 132 108]
 [152 125 102]
 [148 124 103]]
(32, 3)


In [10]:
print(data.train_images[0][0][0]) # [画像の番号][ピクセルの行or列方向指定][ピクセルの列or行方向指定]

[59 62 63]


In [11]:
dlt.utils.plot_examples(data, fname='examples.png')

In [12]:
X_train = data.train_images.reshape([-1, 32, 32, 3])
X_test = data.test_images.reshape([-1, 32, 32, 3])

print('%i training samples' % X_train.shape[0])
print('%i test samples' % X_test.shape[0])

print(X_train.shape)
print(X_test.shape)

50000 training samples
10000 test samples
(50000, 32, 32, 3)
(10000, 32, 32, 3)


In [13]:
dlt.utils.plot_distribution_data(Y=data.train_labels,
                                 dataset_name='y_train',
                                 classes=data.classes,
                                 fname='dist_train.png')

Mean Value: 5000
Median Value: 5000.0
Variance: 0
Standard Deviation: 0.0


In [14]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

In [15]:
print(data.train_labels[:10]) #はじめの10個の画像ラベル

[[6]
 [9]
 [9]
 [4]
 [1]
 [1]
 [2]
 [7]
 [8]
 [3]]
